[project]
name = "uiautomator2-mcp-server"
version = "0.1.0"
description = "uiautomator2 mcp server"
readme = "README.md"
authors = [{ name = "tanbro"}]
requires-python = ">=3.11"
dependencies = ["fastmcp>=2.10,<3.0", "uiautomator2>=3.5,<4.0"]
license = {text = "GPL-3.0-or-later"}

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "u2mcp"

[project.scripts]
u2mcp = "u2mcp.__main__:main"

[dependency-groups]
dev = ["mypy"]