[project]
name = "uiautomator2-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tanbro", email = "tanbro@163.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastmcp[cli]>=2.14.2,<3.0",
    "uiautomator2>=3.5.0.<4.0",
]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
